<?php declare(strict_types=1);
/** @var \MageOS\PasskeyAuth\Block\Login\ConditionalLogin $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="text/x-magento-init">
{
    "*": {
        "MageOS_PasskeyAuth/js/passkey-conditional": {
            "optionsUrl": "<?= $escaper->escapeUrl($block->getOptionsUrl()) ?>",
            "verifyUrl": "<?= $escaper->escapeUrl($block->getVerifyUrl()) ?>",
            "selectors": "#customer-email, #login-email, .block-authentication input[name='username']"
        }
    }
}
</script>
